// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtXmMPa9f-yorklxH4ZCv3gXCVK3tMxFA',
    appId: '1:1032743523064:web:f2eddd8aa213b97807a10d',
    messagingSenderId: '1032743523064',
    projectId: 'speaktotext-ffa7f',
    authDomain: 'speaktotext-ffa7f.firebaseapp.com',
    storageBucket: 'speaktotext-ffa7f.appspot.com',
    measurementId: 'G-PTGZS8FJJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0mL_4hm8SPVHzcBwTbbgqCKeyTZken5w',
    appId: '1:1032743523064:android:2d3234e01810658507a10d',
    messagingSenderId: '1032743523064',
    projectId: 'speaktotext-ffa7f',
    storageBucket: 'speaktotext-ffa7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVo7mcm_5JbP8gFbfUhlY8C72-lp_i3x0',
    appId: '1:1032743523064:ios:25d18f42ebf9614307a10d',
    messagingSenderId: '1032743523064',
    projectId: 'speaktotext-ffa7f',
    storageBucket: 'speaktotext-ffa7f.appspot.com',
    iosBundleId: 'com.example.speak2text',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVo7mcm_5JbP8gFbfUhlY8C72-lp_i3x0',
    appId: '1:1032743523064:ios:69a1a72e42ea087307a10d',
    messagingSenderId: '1032743523064',
    projectId: 'speaktotext-ffa7f',
    storageBucket: 'speaktotext-ffa7f.appspot.com',
    iosBundleId: 'com.example.speak2text.RunnerTests',
  );
}
